### ISSUE TITLE
[DevReport] Internal error is given when running certain commands twice

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions_new#80] opened 2023-08-06 00:38 UTC
## Description
Command that have too few arguments will show the error message in the language file the first time but when reran it has an internal error. Plugin still runs however

## Steps to reproduce
1. run a command like `/f invite` with no arguments
2. See the translated error message
3. Run the command again
4. See the internal exception.

## Logs
```
[01:34:19 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin ImprovedFactions v1.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1003) ~[paper-1.20.1.jar:git-Paper-61]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-61]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2299) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2259) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-61]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-61]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-61]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-61]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at io.github.toberocat.improvedfactions.commands.invite.InviteCommand.handle(InviteCommand.kt:23) ~[ImprovedFactionsBase-v2.0.0-stable-dev.jar:?]
        at io.github.toberocat.toberocore.command.PlayerSubCommand.handleCommand(PlayerSubCommand.java:37) ~[ImprovedFactionsBase-v2.0.0-stable-dev.jar:?]
        at io.github.toberocat.toberocore.command.SubCommand.handleWithOptions(SubCommand.java:92) ~[ImprovedFactionsBase-v2.0.0-stable-dev.jar:?]
        at io.github.toberocat.toberocore.command.SubCommand.routeCall(SubCommand.java:74) ~[ImprovedFactionsBase-v2.0.0-stable-dev.jar:?]
        at io.github.toberocat.toberocore.command.CommandExecutor.onCommand(CommandExecutor.java:41) ~[ImprovedFactionsBase-v2.0.0-stable-dev.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```

**Comment by ToberoCat** [comment] 2023-08-06 11:34
Fixed the issue. It has been caused by the anti spam protection system, which had a small cooldown implemented to prevent messages being spammed.
This cooldown, when actvie, prevented the command options (The things responsible for defining how commands look like) from interupting the command execution.

Should be fixed with the next stable dev version

**Closed by ToberoCat** 2023-08-06 11:34 UTC
Labels: dev-report
